# Site settings
title: WAI Redesign Personas [DRAFT]
email: public-wai-eo-site@w3.org
description: > # this means to ignore newlines until "baseurl:"
  This is a collection of personas to lead the redesign of the W3C WAI website.
baseurl: "/wai-website-personas/" # the subpath of your site, e.g. /blog/
url: "https://w3.org/WAI/" # the base hostname & protocol for your site
twitter_username: w3c_wai
github_username:  w3c

# Build settings
markdown: kramdown

collections:
  personas:
    output: true